-- AlterTable
ALTER TABLE "Url" ADD COLUMN     "clickCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastVisited" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
